### ISSUE TITLE
The Design approach

### ISSUE THREAD

**Issue by Lleutch** [elmish/Uil#1]
The approach for that library will be the following : 
1. Create a branch where I will commit the current state as found on the repo [ElmishWPFLearning](https://github.com/Lleutch/ElmishWPFLearning) (only the DSL part and the VDOM)

2. Discuss if we want to take the route of that branch, or if we want instead to re-wrtie everything from scratch with a different mindset : 
    - Maybe we want a generic way to handle the different view elements using a description fil (.json like in the [Elmish.XamarinForms](https://github.com/fsprojects/Elmish.XamarinForms) repo ?)
     - Maybe we want to abstract the tree diff + VDOM part from the DSL + WPF representation such that the VDOM + tree diff is platform independent ? (if that's even possible ... ) ...

3. As the main purpose of that library is to be used by Elmish.WPF, assess the work needed for Uil to be usable and as performant as possible there. Maybe look at how it is done in [ElmishWPFLearning](https://github.com/Lleutch/ElmishWPFLearning), as it was developped to perform well with the event loop done over there. The Purpose being to make the better use of what we have 😄  
    - For instance, some performance analysis has been done there, showing that the refresh rate is quite fast. Example of such thing is, running a Voice-recorder application were we have an FFT graph of your voice is shown (100 kHz , 512 samples per FFT => a pretty descent refresh rate and no latency)
    
@et1975 There might be other points to discuss there but what do you think of this as the approach to be taken? 

P.S: It might look like I am a bit reluctant to implement the DSL, but in fact it is just that I feel that there is something I am missing (I do not have the whole overview yet and need to integrate it with [Elmish.WPF](https://github.com/elmish/Elmish.WPF) ). Anyway, it's going to be great hopefully 😄 .

**Comment by et1975** [comment]
@Lleutch Thanks for embarking on it!
As I mentioned in the other thread  I no longer think the static views of Elmish.WPF approach can be reconciled with the idea of dynamic views you are pursuing. I thought the static views was a stepping stone, but people seem to like it for what it is. 
At this point I think we need both and I think they need to stay separate. Elmish org is a fiefdom where every repo owner decides for himself which goals to pursue and how he wants to go about them. My single hope is that we can all contribute towards better "model-view-update" architecture by cross-pollinating, experimenting freely and hopefully adopting the best ideas across all the projects.

On the topic of diffing, I'd focus on your WPF-specific diffing at this point. If some abstractions/implementations come up that appear to be universal they can be adopted and refined as needed to other spaces.

Regarding the DSL, I feel like your custom DSL (and that of EXF approach) is a good start, but long term I feel the DSL needs to be "generatable" (via type providers) to be universally useful. The idea being - I can point it at a DLL and it will find all the controls and examine their properties. I haven't done WPF in a while though, so I might be delusional. However, I'd start by looking at [Microsoft's RN fork](/Microsoft/react-native-windows) as they already do a lot of interesting things with windows controls.

**Comment by Lleutch** [comment]
Thanks for the reply. 100% with you on the approach!!
 
Therefore, I will potentially go that route of having something, that I feel makes sense.
And then as time will go by, we'll find ways to improve it, step by step, until we might have, hopefully, something that could potentially interest and help people in any possible way 😄 

Let see how this will end up.
